networks:
  hasher:
    internal: true
  redis:
    internal: true
  rng:
    internal: true
services:
  hasher:
    deploy:
      placement:
        constraints:
        - node.role == worker
    image: academiaonline/dca-dockercoins:latest-hasher
    networks:
    - hasher
  redis:
    deploy:
      placement:
        constraints:
        - node.role == worker  
    image: redis
    networks:
    - redis
  rng:
    deploy:
      placement:
        constraints:
        - node.role == worker
    image: academiaonline/dca-dockercoins:latest-rng
    networks:
    - rng
  webui:
    deploy:
      placement:
        constraints:
        - node.role == worker
    image: academiaonline/dca-dockercoins:latest-webui
    networks:
    - redis
  worker:
    deploy:
      placement:
        constraints:
        - node.role == worker
    image: academiaonline/dca-dockercoins:latest-worker
    networks:
    - hasher
    - redis
    - rng
version: '3.8'    
